name: Documentation Improvement
description: Report an improvement related to the documentation.
title: "[DOCUMENTATION]: << Please use a comprehensive title... >>"
labels: [Documentation]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a documentation improvement request. Before continuing, please take some time to check for existing [issues](https://github.com/colour-science/colour/issues).

  - type: input
    attributes:
      label: Documentation Link
      description: >
        Please link to any documentation or examples that you are referencing. Suggested improvements should be based on the [development version of the documentation](https://colour.readthedocs.io/en/develop/).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: >
        Please describe how the documentation could be improved, what is missing, unclear or incorrect.
      placeholder: >
        * I found [...] to be unclear because [...]
        * [...] made me think that [...] when really it should be [...]
        * There is no example showing how to do [...]
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      placeholder: |
        * This line should be be changed to say [...]
        * Include a paragraph explaining [...]

  - type: textarea
    attributes:
      label: "Environment Information"
      description: If possible, please paste the output from `import colour; colour.utilities.describe_environment()`.
      render: shell
