name: Question
description: Ask a question.
title: "[DISCUSSION]: << Please use a comprehensive title... >>"
labels: [Discussion]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to ask a question or discuss. Before continuing, we would prefer that you start a discussion in the dedicated [discussions](https://github.com/colour-science/colour/discussions) section.
